# Generated by Django 4.0.6 on 2022-12-15 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 9, 40, 9, 930228, tzinfo=utc)),
        ),
    ]
